const traducoes = {
  pt: {
    primeiroNome: "Primeiro Nome",
    ultimoNome: "Último Nome",
    localNascimento: "Local de Nascimento",
    dataNascimento: "Data de Nascimento (dia/mês/ano)",
    nacionalidade: "Nacionalidade",
    idNumber: "Número de Identificação",
    countryDocument: "País do Documento",
    idType: "Tipo de Documento",
    countryResidence: "País de Residência",
    placeResidence: "Morada de Residência",
    arrivalTime: "Hora de Chegada",
    email: "Deixe o seu email se quiser manter contacto:",
    enviar: "Enviar",
    sucesso: "Check-in enviado com sucesso!",
    erroEnvio: "Erro ao enviar o formulário. Tente novamente.",
    erroFetch: "Erro de rede. Tente novamente.",
    erroCamposObrigatorios: "Por favor preencha todos os campos obrigatórios.",
    erroEmail: "Email inválido.",
    preenchaCampo: "Preencha este campo",
    numeroInvalido: "Número inválido",
    emailInvalidoCurto: "Email inválido",
    dataInvalidaCurta: "Data inválida",
    erroFatura: "Por favor preencha os campos obrigatórios para a fatura.",
    faturaCheckbox: "Deseja fatura com contribuinte?",
    faturaSim: "Sim",
    faturaNao: "Não",
    nomeFatura: "Nome",
    nifFatura: "NIF *",
    moradaFatura: "Morada",
    codpostalFatura: "Código Postal",
    cidadeFatura: "Cidade",
    paisFatura: "País *",
    emailFatura: "Email para envio da fatura *",
    lerDocumento: "Ler documento",
    mrzTitulo: "Ler documento",
    mrzSubtitulo: "Aponte a câmara para que a zona MRZ ocupe a moldura. No upload, envie uma foto onde as linhas MRZ estejam bem visíveis.",
    mrzImagemAlt: "Exemplo da zona MRZ no documento",
    uploadFoto: "Upload da foto",
    usarCamera: "Usar câmara",
    trocarCamera: "Trocar camera",
    capturarFoto: "Capturar foto",
    fechar: "Fechar",
    progresso: "Progresso",
    leituraSucesso: "Documento lido com sucesso. Confirme os dados preenchidos no formulário.",
    leituraFalhou: "Não foi possível ler a MRZ. Tente novamente com uma foto mais nítida e aproximada da zona MRZ.",
    obrigadoTitulo: "Obrigado",
    obrigadoMensagem: "O formulário foi enviado com sucesso! Obrigado pela colaboração :)",
    adicionarHospede: "Adicionar outro hóspede",
    erroIdReserva: "ID da Reserva não identificado. Volte a abrir o link enviado ou contacte o anfitrião. Obrigado.",
    erroDataNascimento: "Data de Nascimento inválida.",
    erroIdDocumento: "Confirme o número de identificação. Deve ter pelo menos 4 caracteres, letras/números, e não pode ser uma sequência repetida ou genérica.",
    enviar: "Enviar",
    enviando: "Enviando...",
    cabecalho: `
      <h2>Boletim de Alojamento</h2>
      <p>Em Portugal, assim como na maioria dos países europeus, todos os estabelecimentos de alojamento pago devem registar a estadia e recolher dados de identificação de todos os cidadãos, sejam eles de Estados-Membros da União Europeia ou de Países Terceiros, para comunicar ao Serviço de Estrangeiros e Fronteiras no prazo de três dias.</p>
      <p>Todos os dados pessoais fornecidos serão tratados em conformidade com o Regulamento Geral sobre a Proteção de Dados (RGPD - UE 2016/679).</p>
      <p><strong><a href="https://alojamento-ninho.pt/Terms-Policies" target="_blank">Termos e Condições</a></strong></p>
    `
  },
  en: {
    primeiroNome: "First Name",
    ultimoNome: "Last Name",
    localNascimento: "Place of Birth",
    dataNascimento: "Date of Birth (day/month/year)",
    nacionalidade: "Nationality",
    idNumber: "ID Number",
    countryDocument: "Country of Document",
    idType: "ID Type",
    countryResidence: "Country of Residence",
    placeResidence: "Place of Residence",
    arrivalTime: "Arrival Time",
    email: "Leave your email if you want to stay in touch!",
    enviar: "Submit",
    sucesso: "Check-in submitted successfully!",
    erroEnvio: "Error submitting the form. Please try again.",
    erroFetch: "Network error. Please try again.",
    erroCamposObrigatorios: "Please fill in all required fields.",
    erroEmail: "Invalid email.",
    preenchaCampo: "Fill in this field",
    numeroInvalido: "Invalid number",
    emailInvalidoCurto: "Invalid email",
    dataInvalidaCurta: "Invalid date",
    erroFatura: "Please fill in the required invoice fields.",
    faturaCheckbox: "Would you like an invoice with tax ID?",
    faturaSim: "Yes",
    faturaNao: "No",
    nomeFatura: "Name",
    nifFatura: "Tax ID *",
    moradaFatura: "Address",
    codpostalFatura: "Postal Code",
    cidadeFatura: "City",
    paisFatura: "Country *",
    emailFatura: "Invoice email *",
    lerDocumento: "Read document",
    mrzTitulo: "Read document",
    mrzSubtitulo: "Point the camera so the MRZ area fits inside the frame. For upload, send a photo where the MRZ lines are clearly visible.",
    mrzImagemAlt: "Example of the MRZ area on the document",
    uploadFoto: "Upload photo",
    usarCamera: "Use camera",
    trocarCamera: "Switch camera",
    capturarFoto: "Capture photo",
    fechar: "Close",
    progresso: "Progress",
    leituraSucesso: "Document read successfully. Please check the filled form fields.",
    leituraFalhou: "Could not read the MRZ. Please try again with a clearer photo focused on the MRZ area.",
    obrigadoTitulo: "Thank you",
    obrigadoMensagem: "The form was submitted successfully! Thank you for your cooperation :)",
    adicionarHospede: "Add another guest",
    erroIdReserva: "Reservation ID not identified. Please reopen the link sent or contact the host. Thank you.",
    erroDataNascimento: "Invalid Date of Birth.",
    erroIdDocumento: "Please check the ID number. It must have at least 4 characters, letters/numbers, and cannot be a repeated or generic sequence.",
    enviar: "Submit",
    enviando: "Sending...",
    cabecalho: `
      <h2>Accommodation Bulletin</h2>
      <p>In Portugal, as well as in most European countries, all paid accommodation establishments need to record the stay and collect identification details from all citizens, whether they are from Member States of the European Union or Third Country Nationals, in order to communicate them within three days to the Immigration and Borders Service.</p>
      <p>Any personal data provided will be processed in accordance with the General Data Protection Regulation (GDPR - EU 2016/679).</p>
      <p><strong><a href="https://alojamento-ninho.pt/Terms-Policies" target="_blank">Terms and Conditions</a></strong></p>
    `
  },
  fr: {
    primeiroNome: "Prénom",
    ultimoNome: "Nom de famille",
    localNascimento: "Lieu de naissance",
    dataNascimento: "Date de naissance (jour/mois/année)",
    nacionalidade: "Nationalité",
    idNumber: "Numéro d'identité",
    countryDocument: "Pays du document",
    idType: "Type de document",
    countryResidence: "Pays de résidence",
    placeResidence: "Lieu de résidence",
    arrivalTime: "Heure d'arrivée",
    email: "Laissez votre e-mail si vous souhaitez rester en contact !",
    enviar: "Envoyer",
    sucesso: "Formulaire envoyé avec succès !",
    erroEnvio: "Erreur lors de l'envoi du formulaire. Veuillez réessayer.",
    erroFetch: "Erreur de réseau. Veuillez réessayer.",
    erroCamposObrigatorios: "Veuillez remplir tous les champs obligatoires.",
    erroEmail: "Email invalide.",
    preenchaCampo: "Remplissez ce champ",
    numeroInvalido: "Numéro invalide",
    emailInvalidoCurto: "Email invalide",
    dataInvalidaCurta: "Date invalide",
    erroFatura: "Veuillez remplir les champs obligatoires pour la facture.",
    faturaCheckbox: "Souhaitez-vous une facture avec numéro fiscal ?",
    faturaSim: "Oui",
    faturaNao: "Non",
    nomeFatura: "Nom",
    nifFatura: "Numéro fiscal *",
    moradaFatura: "Adresse",
    codpostalFatura: "Code Postal",
    cidadeFatura: "Ville",
    paisFatura: "Pays *",
    emailFatura: "Email pour l'envoi de la facture *",
    lerDocumento: "Lire le document",
    mrzTitulo: "Lire le document",
    mrzSubtitulo: "Orientez la caméra pour que la zone MRZ soit dans le cadre. Pour l'upload, envoyez une photo où les lignes MRZ sont bien visibles.",
    mrzImagemAlt: "Exemple de zone MRZ sur le document",
    uploadFoto: "Importer la photo",
    usarCamera: "Utiliser la caméra",
    trocarCamera: "Changer camera",
    capturarFoto: "Capturer la photo",
    fechar: "Fermer",
    progresso: "Progression",
    leituraSucesso: "Document lu avec succès. Vérifiez les champs remplis dans le formulaire.",
    leituraFalhou: "Impossible de lire la MRZ. Réessayez avec une photo plus nette et rapprochée de la zone MRZ.",
    obrigadoTitulo: "Merci",
    obrigadoMensagem: "Le formulaire a été envoyé avec succès ! Merci pour votre collaboration :)",
    adicionarHospede: "Ajouter un autre hôte",
    erroIdReserva: "Identifiant de réservation non identifié. Veuillez rouvrir le lien envoyé ou contacter l’hôte. Merci.",
    erroDataNascimento: "Date de naissance invalide.",
    erroIdDocumento: "Veuillez vérifier le numéro d’identification. Il doit contenir au moins 4 caractères, lettres/chiffres, et ne peut pas être une séquence répétée ou générique.",
    enviar: "Envoyer",
    enviando: "Envoi en cours...",
    cabecalho: `
      <h2>Bulletin d'Hébergement</h2>
      <p>Au Portugal, comme dans la plupart des pays européens, tous les établissements d'hébergement payants doivent enregistrer le séjour et collecter les informations d'identification de tous les citoyens, qu'ils soient ressortissants de l'Union européenne ou de pays tiers, afin de les communiquer dans un délai de trois jours au Service de l'immigration et des frontières.</p>
      <p>Toutes les données personnelles fournies seront traitées conformément au Règlement Général sur la Protection des Données (RGPD - UE 2016/679).</p>
      <p><strong><a href="https://alojamento-ninho.pt/Terms-Policies" target="_blank">Conditions générales</a></strong></p>
    `
  },
  es: {
    primeiroNome: "Nombre",
    ultimoNome: "Apellido",
    localNascimento: "Lugar de nacimiento",
    dataNascimento: "Fecha de nacimiento (día/mes/año)",
    nacionalidade: "Nacionalidad",
    idNumber: "Número de Identificación",
    countryDocument: "País del documento",
    idType: "Tipo de documento",
    countryResidence: "País de residencia",
    placeResidence: "Lugar de residencia",
    arrivalTime: "Hora de llegada",
    email: "¡Deja tu correo si quieres mantener el contacto!",
    enviar: "Enviar",
    sucesso: "¡Formulario enviado correctamente!",
    erroEnvio: "Error al enviar el formulario. Inténtalo de nuevo.",
    erroFetch: "Error de red. Inténtalo de nuevo.",
    erroCamposObrigatorios: "Por favor, rellena todos los campos obligatorios.",
    erroEmail: "Correo electrónico no válido.",
    preenchaCampo: "Rellena este campo",
    numeroInvalido: "Número inválido",
    emailInvalidoCurto: "Correo inválido",
    dataInvalidaCurta: "Fecha inválida",
    erroFatura: "Por favor, rellene los campos obligatorios para la factura.",
    faturaCheckbox: "¿Desea factura con NIF?",
    faturaSim: "Sí",
    faturaNao: "No",
    nomeFatura: "Nombre",
    nifFatura: "NIF *",
    moradaFatura: "Dirección",
    codpostalFatura: "Código Postal",
    cidadeFatura: "Ciudad",
    paisFatura: "País *",
    emailFatura: "Correo para envío de la factura *",
    lerDocumento: "Leer documento",
    mrzTitulo: "Leer documento",
    mrzSubtitulo: "Apunta la cámara para que la zona MRZ quede dentro del marco. Para subir una foto, envía una imagen donde las líneas MRZ sean claramente visibles.",
    mrzImagemAlt: "Ejemplo de la zona MRZ en el documento",
    uploadFoto: "Subir foto",
    usarCamera: "Usar cámara",
    trocarCamera: "Cambiar camara",
    capturarFoto: "Capturar foto",
    fechar: "Cerrar",
    progresso: "Progreso",
    leituraSucesso: "Documento leído correctamente. Revisa los campos rellenados en el formulario.",
    leituraFalhou: "No se pudo leer la MRZ. Inténtalo de nuevo con una foto más nítida y cercana de la zona MRZ.",
    obrigadoTitulo: "Gracias",
    obrigadoMensagem: "El formulario se ha enviado correctamente. Gracias por tu colaboración :)",
    adicionarHospede: "Añadir otro huésped",
    erroIdReserva: "ID de reserva no identificado. Vuelva a abrir el enlace enviado o contacte con el anfitrión. Gracias.",
    erroDataNascimento: "Fecha de nacimiento no válida.",
    erroIdDocumento: "Comprueba el número de identificación. Debe tener al menos 4 caracteres, letras/números, y no puede ser una secuencia repetida o genérica.",
    enviar: "Enviar",
    enviando: "Enviando...",
    cabecalho: `
      <h2>Boletín de Alojamiento</h2>
      <p>En Portugal, al igual que en la mayoría de los países europeos, todos los alojamientos de pago deben registrar la estancia y recopilar los datos de identificación de todos los ciudadanos, ya sean de Estados miembros de la Unión Europea o de países terceros, con el fin de comunicarlos en un plazo de tres días al Servicio de Inmigración y Fronteras.</p>
      <p>Todos los datos personales proporcionados serán tratados de acuerdo con el Reglamento General de Protección de Datos (RGPD - UE 2016/679).</p>
      <p><strong><a href="https://alojamento-ninho.pt/Terms-Policies" target="_blank">Términos y Condiciones</a></strong></p>
    `
  }
};
